In [6]:
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
df = pd.read_excel("region_wise_sales.xlsx")
df

        Month  Year    Region  Sales
0     January  2022      APAC  36750
1    February  2022      APAC  36995
2       March  2022      APAC  18579
3       April  2022      APAC  37768
4         May  2022      APAC  23956
5        June  2022      APAC  38143
6        July  2022      APAC  29132
7      August  2022      APAC  21961
8   September  2022      APAC  33299
9     October  2022      APAC  37279
10   November  2022      APAC  21388
11   December  2022      APAC  21896
12    January  2022    Europe   9665
13   February  2022    Europe  10297
14      March  2022    Europe  11079
15      April  2022    Europe  13410
16        May  2022    Europe  11229
17       June  2022    Europe  15352
18       July  2022    Europe  13286
19     August  2022    Europe  11470
20  September  2022    Europe  11873
21    October  2022    Europe  23000
22   November  2022    Europe  12215
23   December  2022    Europe  14895
24    January  2022  Americas  30247
25   February  2022  Americas  29284
26      March  2022  Americas  27904
27      April  2022  Americas  23407
28        May  2022  Americas  23716
29       June  2022  Americas  25077
30       July  2022  Americas  33649
31     August  2022  Americas  24560
32  September  2022  Americas  34102
33    October  2022  Americas  28257
34   November  2022  Americas  30691
35   December  2022  Americas  29387

In [8]:
df.shape

(36, 4)

In [11]:
df.Region.unique()

array(['APAC', 'Europe', 'Americas'], dtype=object)

In [13]:
df_apac = df[df.Region == "APAC"]
df_apac

        Month  Year Region  Sales
0     January  2022   APAC  36750
1    February  2022   APAC  36995
2       March  2022   APAC  18579
3       April  2022   APAC  37768
4         May  2022   APAC  23956
5        June  2022   APAC  38143
6        July  2022   APAC  29132
7      August  2022   APAC  21961
8   September  2022   APAC  33299
9     October  2022   APAC  37279
10   November  2022   APAC  21388
11   December  2022   APAC  21896

In [15]:
df_Europe = df[df.Region == "Europe"]
df_Europe

        Month  Year  Region  Sales
12    January  2022  Europe   9665
13   February  2022  Europe  10297
14      March  2022  Europe  11079
15      April  2022  Europe  13410
16        May  2022  Europe  11229
17       June  2022  Europe  15352
18       July  2022  Europe  13286
19     August  2022  Europe  11470
20  September  2022  Europe  11873
21    October  2022  Europe  23000
22   November  2022  Europe  12215
23   December  2022  Europe  14895

In [14]:
df_Americas = df[df.Region == "Americas"]
df_Americas

        Month  Year    Region  Sales
24    January  2022  Americas  30247
25   February  2022  Americas  29284
26      March  2022  Americas  27904
27      April  2022  Americas  23407
28        May  2022  Americas  23716
29       June  2022  Americas  25077
30       July  2022  Americas  33649
31     August  2022  Americas  24560
32  September  2022  Americas  34102
33    October  2022  Americas  28257
34   November  2022  Americas  30691
35   December  2022  Americas  29387

In [21]:
def get_lower_upper(data):
    Q1,Q3 = data.Sales.quantile([0.25,0.75])
    IQR = Q3 - Q1
    lower = Q1 - 1.5*IQR
    upper = Q3 + 1.5*IQR
    return lower,upper

In [22]:
lower , upper = get_lower_upper(df_apac)
lower , upper

(-737.125, 59747.875)

In [23]:
df_apact

NameError: name 'df_apact' is not defined