In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("heights.csv")
df

       name  height
0     mohan     1.2
1     maria     4.6
2     sakib     4.9
3       tao     5.1
4     virat     5.2
5    khusbu     5.4
6    dmitry     5.5
7    selena     5.5
8      john     5.6
9     imran     5.6
10     jose     5.8
11  deepika     5.9
12   yoseph     6.0
13    binod     6.1
14  gulshan     6.2
15  johnson     6.5
16   donald     6.6
17    aamir     7.1
18      ken     7.1
19      Liu    40.2

In [ ]:
# # def get_lower_upper(x):
    
#     IQR = Q3 -Q1
#     lower_limit = Q1 - 1.5*IQR
#     upper_limit = Q3 + 1.5*IQR
#     return lower_limit,upper_limit

In [14]:
Q1,Q3 = df.height.quantile([0.25,0.75])
Q1,Q3

(5.3500000000000005, 6.275)

In [16]:
IQR = Q3 -Q1
IQR

0.9249999999999998

In [20]:
lower_limit = Q1 - 1.5*IQR
lower_limit
upper_limit = Q3 + 1.5*IQR

In [21]:
df[(df.height < lower_limit) |(df.height > upper_limit)]

     name  height
0   mohan     1.2
19    Liu    40.2

In [24]:
new_df = df[(df.height > lower_limit) &(df.height < upper_limit)]
new_df

       name  height
1     maria     4.6
2     sakib     4.9
3       tao     5.1
4     virat     5.2
5    khusbu     5.4
6    dmitry     5.5
7    selena     5.5
8      john     5.6
9     imran     5.6
10     jose     5.8
11  deepika     5.9
12   yoseph     6.0
13    binod     6.1
14  gulshan     6.2
15  johnson     6.5
16   donald     6.6
17    aamir     7.1
18      ken     7.1